# Generated by Django 3.2.9 on 2021-12-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0002_auto_20211216_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='Invested_Amt',
        ),
    ]
