# Generated by Django 3.2.9 on 2021-12-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0004_alter_bank_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='Last_Name',
            field=models.CharField(max_length=1000),
        ),
    ]
