# Generated by Django 3.2.9 on 2021-12-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0005_alter_investor_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Account_no',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Name',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ISIN',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
