# Generated by Django 3.2.9 on 2022-02-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0006_auto_20211220_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Username',
            field=models.ForeignKey(default='empty', on_delete=django.db.models.deletion.CASCADE, to='databases.investor', unique=True),
        ),
    ]
