# Generated by Django 3.2.9 on 2022-02-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_alter_bank_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='Transaction',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=20),
        ),
        migrations.AddField(
            model_name='investor',
            name='Stocks_Purchased',
            field=models.IntegerField(default=0),
        ),
    ]
