# Generated by Django 3.2.9 on 2022-02-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0008_auto_20220210_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='Stocks_Purchased',
        ),
    ]
