# Generated by Django 3.2.9 on 2022-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0009_remove_investor_stocks_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='Transaction',
            field=models.CharField(default='Buy', max_length=20),
        ),
    ]
