# Generated by Django 3.2.9 on 2022-02-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0010_alter_investment_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='Transaction',
            new_name='Transaction_Mode',
        ),
    ]
