# Generated by Django 3.2.9 on 2022-03-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0011_rename_transaction_investment_transaction_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='First_Name',
            field=models.CharField(max_length=1000),
        ),
    ]
